BestRestaurantApp/Models/BestRestaurantContext.cs
using Microsoft.EntityFrameworkCore;

namespace BestRestaurantApp.Models
{
    public class BestRestaurantContext : DbContext
    {
        public DbSet<Cuisine> Cuisines { get; set; }
        public DbSet<Restaurant> Restaurants { get; set; }

        public BestRestaurantContext(DbContextOptions options) : base(options) { }
    }
}

BestRestaurantApp/Models/Cuisine.cs
using MySqlConnector;

namespace BestRestaurantApp.Models
{

  public class Cuisine
  {

    public int CuisineId { get; set; }
    public string Type { get; set; }

    public List<Restaurant> Restaurants { get; set; }
  }
}

BestRestaurantApp/Models/Restaurant.cs
using MySqlConnector;

namespace BestRestaurantApp.Models {
    public class Restaurant {
        public int RestaurantId {get; set;}
        public string Name {get; set;}
        public string Address {get; set;}
        public string Rating {get; set;}
        public int CuisineId {get; set;}
        public Cuisine Cuisine { get; set; }
    }
    
}

BestRestaurantApp/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using BestRestaurantApp.Models;

namespace BestRestaurantApp.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly BestRestaurantContext _db;

    public CuisinesController(BestRestaurantContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine)
    {
      _db.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet("/Cuisines/{id}/delete")]
    public ActionResult Delete(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(thisCuisine);
    }

    [HttpPost("/Cuisines/{id}/delete/confirm")]
    public ActionResult Confirm(int id)
    {
      Cuisine thisCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      List<Restaurant> thisRestaurants = _db.Restaurants.ToList();
      foreach (Restaurant delRest in thisRestaurants)
      {
        if (delRest.CuisineId == id)
        {
          _db.Restaurants.Remove(delRest);
        }
      }
      _db.Cuisines.Remove(thisCuisine);
      _db.SaveChanges();
      return Redirect("/Cuisines/");
    }

    public ActionResult Details(int id)
    {
      Cuisine thisCuisine = _db.Cuisines
        .Include(cuisine => cuisine.Restaurants) 
        .FirstOrDefault(cuisine => cuisine.CuisineId == id); 
      List<Restaurant> dbRests = _db.Restaurants.ToList();
      thisCuisine.Restaurants = new List<Restaurant>{};
      foreach (Restaurant rest in dbRests)
      {
        if (rest.CuisineId == thisCuisine.CuisineId) 
        {
          thisCuisine.Restaurants.Add(rest);
        }
      }
        return View(thisCuisine);
    }
  }
}

BestRestaurantApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurantApp.Models;

namespace BestRestaurantApp.Controllers
{
  public class HomeController : Controller
  {
    [Route("/")]
    public ActionResult Index() {
      return View();
    }
  }
}

BestRestaurantApp/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using BestRestaurantApp.Models;
using System.Collections.Generic;
using System.Linq;

namespace BestRestaurantApp.Controllers
{
  public class RestaurantController : Controller
  {
    private readonly BestRestaurantContext _db;

    public RestaurantController(BestRestaurantContext db)
    {
      _db = db;
    }

    [HttpGet("/restaurants/{id}/delete")]
    public ActionResult Delete(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(thisRestaurant);
    }

    [HttpGet("/restaurants/details")]
    public ActionResult Details(string search)
    {
      List<Restaurant> thisRestaurant = _db.Restaurants
        .Where(restaurant => restaurant.Name.Contains(search))
        .ToList();
      List<Cuisine> cuisines = _db.Cuisines.ToList();
      ViewBag.Cuisines = cuisines;

      return View(thisRestaurant);
    }

    [HttpPost("/restaurants/{id}/delete/confirm")]
    public ActionResult Confirm(int id)
    {
      Restaurant thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(thisRestaurant);
      _db.SaveChanges();
      return Redirect($"/Cuisines/Details/{thisRestaurant.CuisineId}");
    }

    [HttpPost("/restaurants/{id}/create")]
    public ActionResult Create(int id, Restaurant restaurant)
    {
      restaurant.CuisineId = id;
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return Redirect($"/Cuisines/Details/{id}");
    }
  }
}

BestRestaurantApp/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

<div class="form-group text-center w-25 m-auto">
  <form action="/cuisines/create" method="post">
    <label class="form-label" for="Type">Type</label>
    <input class="form-control" type="text" name="Type" id="Type">
    <br>
    <button class="form-control btn btn-light" type="submit">Add Cuisine</button>
  </form>
</div>

@* @model BestRestaurantApp.Models.Cuisine

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Type)
  @Html.TextBoxFor(model => model.Type)
  <input type="submit" value="Add Cuisine"/>
} *@

BestRestaurantApp/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

<h2 style="text-align: center;">Are you sure you want to delete <span id="delete">@Model.Type</span>?<h2>

    <form class="text-center" action="/Cuisines/@Model.CuisineId/delete/confirm" method="post">
      <button class="btn btn-danger" type="submit">Delete Cuisine</button>
      <a class="btn btn-warning" href="/Cuisines/Details/@Model.CuisineId">Cancel</a>
    </form>

BestRestaurantApp/Views/Cuisines/Details.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurantApp.Models;

<div class="row">
  <div class="col-8">
    <h1 class="text-center">@Model.Type</h1>
    <div class="row">
      @foreach (Restaurant rest in Model.Restaurants)
      {        
        <div class="col-12">
          <div class="card text-center">
            <div class="card-body">
              <h3 class="card-title">
                Name: @rest.Name
              </h3>
              <p class="card-text">
                Address: @rest.Address
              </p>
              <p class="card-text">
                Rating: @rest.Rating
              </p>
              <a class="button btn btn-danger w-25" href="/restaurants/@rest.RestaurantId/delete">Delete</a>
            </div>
          </div>
        </div>
      }
    </div>
  </div>
  <div class="col-4 stick">
    <div class="form-group">
      <form action="/restaurants/@Model.CuisineId/create" method="post">
        <label class="form-label" for="Name">Restaurant Name</label>
        <input class="form-control" type="text" name="Name" id="Name">
        <br>
        <label class="form-label" for="Address">Address:</label>
        <input class="form-control" type="text" name="Address" id="Address">
        <br>
        <label class="form-label" for="Rating">Rating</label>
        <input class="form-control" type="text" name="Rating" id="Rating">
        <br>
        <button class="form-control btn btn-warning" type="submit">Add A Restaurant</button>
        <a class="button btn btn-info" href="/Cuisines">See all cuisines</a>
        <a class="button btn btn-danger" href="/Cuisines/@Model.CuisineId/delete">Delete Cuisine</a>
      </form>
    </div>
  </div>
</div>

BestRestaurantApp/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurantApp.Models;
<div class="row">
  <div class="col-6">
    <h1 class="text-center">Cuisines</h1>

    @if (Model.Count == 0)
    {
      <p>No cuisines have been added yet!</p>
    }
    else
    {
      <ul class="list-group mt-4">
      @foreach (Cuisine cuisine in Model)
      {
        <li class="list-group-item text-center w-75 m-auto">@Html.ActionLink($"{cuisine.Type}", "Details", new { id = cuisine.CuisineId })</li>
      }
      </ul>
    }
    <div class="w-50 m-auto mt-3">
      <a class="button btn btn-info" href="/Cuisines/create">Add new Cuisine</a>
    </div>

  </div>
  <div class="col-6">
    <form action="/restaurants/details" method="get">
        <label class="form-label" for="search">Search for a restaurant:</label>
        <input class="form-control" type="text" name="search" id="search">
        <br>
        <button class="form-control btn btn-success" type="submit">Search</button>
      </form>
  </div>
</div>

BestRestaurantApp/Views/Home/index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to the best restaurants app!</h1>

<p>@Html.ActionLink("See all cuisines", "Index", "Cuisines")</p>
<p>@Html.ActionLink("Add a new cuisine", "Create", "Cuisines")</p>

BestRestaurantApp/Views/Restaurant/Delete.cshtml
@{
  Layout = "_Layout";
}

<h2 style="text-align: center;">Are you sure you want to delete <span id="delete">@Model.Name</span>?<h2>

    <form class="text-center" action="/restaurants/@Model.RestaurantId/delete/confirm" method="post">
      <button class="btn btn-danger" type="submit">Delete Restaurant</button>
      <a class="btn btn-warning" href="/Cuisines/Details/@Model.CuisineId">Cancel</a>
    </form>

BestRestaurantApp/Views/Restaurant/Details.cshtml
@{
  Layout = "_Layout";
}
@using BestRestaurantApp.Models

@foreach (Restaurant rest in Model)
{

  <div class="card text-center">
  <div class="card-body">
      @foreach (Cuisine cuisine in @ViewBag.Cuisines)
      {
        if (@rest.CuisineId == cuisine.CuisineId)
        {
    <h1 class="card=-title">
          Cuisine: @cuisine.Type
    </h1>
        }
      }
    <h3 class="card-title">
      Name: @rest.Name
    </h3>
    <p class="card-text">
      Address: @rest.Address
    </p>
    <p class="card-text">
      Rating: @rest.Rating
    </p>
    <a class="button btn btn-danger w-25" href="/restaurants/@rest.RestaurantId/delete">Delete</a>
  </div>
</div>

}
<div class="w-25 m-auto text-center">
  <a class="button btn btn-info mt-5" href="/Cuisines">See all cuisines</a>
</div>

BestRestaurantApp/Views/Restaurant/create.cshtml
@{
  Layout = "_Layout";
}

<div class="form-group text-center w-25 m-auto">
  <form action="/restaurants/create" method="post">
    <label class="form-label" for="name">Restaurant Name</label>
    <input class="form-control" type="text" name="name" id="name">
    <br>
    <label class="form-label" for="address">Address:</label>
    <input class="form-control" type="text" name="address" id="address">
    <br>
    <label class="form-label" for="rating">Rating</label>
    <input class="form-control" type="text" name="rating" id="rating">
    <br>
    <button class="form-control btn btn-danger" type="submit">Add A Restaurant</button>
  </form>
</div>

BestRestaurantApp/Views/Restaurant/index.cshtml
@{
  Layout = "_Layout";
}

@using BestRestaurantApp.Models;

<h1>Restaurants</h1>

@if (Model.Count == 0)
{
  <p>Where them restaurants be?</p>
}
else
{
  @foreach (Restaurant restaurant in Model)
  {
    <li>@Html.ActionLink($"{restaurant}", "Details", new { id = restaurant.RestaurantId})</li>
  }
}

<p>@Html.ActionLink("Add a new restaurant", "Create", "Restaurant")</p>

BestRestaurantApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css" type="text/css">
  <title>BestRestaurantApp</title>
</head>

<body>
  <div class="container">
    <div class="jumbotron">
      <h1 id="jumbotron">Best Restaurants</h1>
    </div>
    @RenderBody()
  </div>
</body>

</html>